### ISSUE TITLE
能写个简要的readme.txt文档吗？

### ISSUE THREAD

**Issue by USTC-wlsong** [zhangliukun/registration_cnn_ntg#2]

**Comment by zhangliukun** [comment]
@USTC-wlsong
最近工作比较繁忙，我尽量抽空更新写一个简要的文档

**Comment by zhangliukun** [comment]
已更新readme文档。

**Comment by USTC-wlsong** [comment]
> 已更新readme文档。

非常感谢你开源代码和及时的答复更新，能麻烦你给个该开源代码对应的论文链接吗？

**Comment by zhangliukun** [comment]
> 非常感谢你开源代码和及时的答复更新，能麻烦你给个该开源代码对应的论文链接吗？

这个论文链接联系下官网看看能不能获取论文链接，其实主要思想基本看这个poster大致就能明白。实验部分论证了深度方法提供的初始点减少了传统迭代方法获取初始点的错误率，从而提升了总体的精度。另外这个初始点可以减少迭代方法的迭代次数从而加快配准的速度。原论文PDF估计得找一找。。
